name: CI

on: 
  pull_request:
    branches:
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.6"
      - name: Install pipx
        run: |
          python -m pip install --upgrade pip
          pip install --user pipx
          python -m pipx ensurepath
      - name: Install Poetry and Nox
        run: |
          pipx install poetry
          pipx install nox
      - name: Run lint session
        run: nox -s lint

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.6"
      - name: Install pipx
        run: |
          python -m pip install --upgrade pip
          pip install --user pipx
          python -m pipx ensurepath
      - name: Install Poetry and Nox
        run: |
          pipx install poetry==1.8.4
          pipx install nox==2024.4.15
      - name: Run format session
        run: nox -s formatting

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.6"
      - name: Install pipx
        run: |
          python -m pip install --upgrade pip
          pip install --user pipx
          python -m pipx ensurepath
      - name: Install Poetry and Nox
        run: |
          pipx install poetry
          pipx install nox
      - name: Download JAR file
        run: |
          mkdir -p ./libs
          wget -O ./libs/duckdb_jdbc.jar https://repo1.maven.org/maven2/org/duckdb/duckdb_jdbc/1.1.3/duckdb_jdbc-1.1.3.jar
      - name: Run test session
        run: nox -s test

  typing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.6"
      - name: Install pipx
        run: |
          python -m pip install --upgrade pip
          pip install --user pipx
          python -m pipx ensurepath
      - name: Install Poetry and Nox
        run: |
          pipx install poetry
          pipx install nox
      - name: Run typing session
        run: nox -s typing
